"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import { Toaster } from "sonner";
import { DashboardLayout } from "@/widgets";
import { useRouter } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConfigProvider
          theme={{
            token: {
              borderRadius: 4,
              // colorPrimary: "#FDFDFD",
              // colorBgContainer: "#A011FF",
            },
            hashed: false,
          }}
        >
          <Toaster position="top-center" richColors />
          <DashboardLayout router={router}>{children}</DashboardLayout>
        </ConfigProvider>
      </body>
    </html>
  );
}
